---
- name: "Install git"
  become: true
  ansible.builtin.yum:
    name: git
    state: present
- name: "Install epel repo"
  become: true
  ansible.builtin.yum:
    name: epel-release
    state: present
- name: "Install nginx"
  become: true
  ansible.builtin.yum:
    name: nginx
    state: present
- name: "Get Lighthouse from git"
  become: true
  ansible.builtin.git:
    repo: "{{ lighthouse_repo }}"
    version: master
    dest: "{{ lighthouse_path }}"
- name: "Setup lighthouse config"
  become: true
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"
  notify: Restart nginx service
- name: Flush handllush_handleers
  ansible.builtin.meta: flush_handlers
